version: '3.8'

services:
  db1:
    image: postgres:15
    container_name: db1
    environment:
      POSTGRES_DB: db1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"  # WildFly ожидает на этом порту db1
    volumes:
      - db1_data:/var/lib/postgresql/data
    networks:
      - wildfly-network

  db2:
    image: postgres:15
    container_name: db2
    environment:
      POSTGRES_DB: db2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # перенаправляем порт 5433 хоста на 5432 контейнера
    volumes:
      - db2_data:/var/lib/postgresql/data
    networks:
      - wildfly-network

volumes:
  db1_data:
  db2_data:

networks:
  wildfly-network:
    driver: bridge
